version: '3.8'

services:
  data-analyzer-frontend:
    image: data-analyzer-frontend
    ports:
      - "3000:80"
    depends_on:
      - data-analyzer-backend
    networks:
      - data-analyzer-network
    env_file:
      - .env

  data-analyzer-backend:
    image: data-analyzer-backend
    ports:
      - "5000:5000"
    depends_on:
      - data-analyzer-mongo
    networks:
      - data-analyzer-network
    env_file:
      - .env

  data-analyzer-mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - data-analyzer-network

  data-analyzer-nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - data-analyzer-frontend
    networks:
      - data-analyzer-network

networks:
  data-analyzer-network:
    driver: bridge
